// Implementation file for parser generated by fsyacc
module CalcParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 0 " "

# 8 "CalcParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | EQ
  | KW_PRINT
  | KW_LET
  | VNAME of (string)
  | RBR
  | LBR
  | RBRMOD
  | LBRMOD
  | Bin
  | DivRem
  | Pow
  | Mul
  | Div
  | Sub
  | Sum
  | NUM of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_EQ
    | TOKEN_KW_PRINT
    | TOKEN_KW_LET
    | TOKEN_VNAME
    | TOKEN_RBR
    | TOKEN_LBR
    | TOKEN_RBRMOD
    | TOKEN_LBRMOD
    | TOKEN_Bin
    | TOKEN_DivRem
    | TOKEN_Pow
    | TOKEN_Mul
    | TOKEN_Div
    | TOKEN_Sub
    | TOKEN_Sum
    | TOKEN_NUM
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_stmt
    | NONTERM_expression
    | NONTERM_tExpression
    | NONTERM_factor
    | NONTERM_power
    | NONTERM_vname
    | NONTERM_eof

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | EQ  -> 1 
  | KW_PRINT  -> 2 
  | KW_LET  -> 3 
  | VNAME _ -> 4 
  | RBR  -> 5 
  | LBR  -> 6 
  | RBRMOD  -> 7 
  | LBRMOD  -> 8 
  | Bin  -> 9 
  | DivRem  -> 10 
  | Pow  -> 11 
  | Mul  -> 12 
  | Div  -> 13 
  | Sub  -> 14 
  | Sum  -> 15 
  | NUM _ -> 16 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_EQ 
  | 2 -> TOKEN_KW_PRINT 
  | 3 -> TOKEN_KW_LET 
  | 4 -> TOKEN_VNAME 
  | 5 -> TOKEN_RBR 
  | 6 -> TOKEN_LBR 
  | 7 -> TOKEN_RBRMOD 
  | 8 -> TOKEN_LBRMOD 
  | 9 -> TOKEN_Bin 
  | 10 -> TOKEN_DivRem 
  | 11 -> TOKEN_Pow 
  | 12 -> TOKEN_Mul 
  | 13 -> TOKEN_Div 
  | 14 -> TOKEN_Sub 
  | 15 -> TOKEN_Sum 
  | 16 -> TOKEN_NUM 
  | 19 -> TOKEN_end_of_input
  | 17 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_start 
    | 3 -> NONTERM_stmt 
    | 4 -> NONTERM_stmt 
    | 5 -> NONTERM_expression 
    | 6 -> NONTERM_expression 
    | 7 -> NONTERM_expression 
    | 8 -> NONTERM_tExpression 
    | 9 -> NONTERM_tExpression 
    | 10 -> NONTERM_tExpression 
    | 11 -> NONTERM_tExpression 
    | 12 -> NONTERM_factor 
    | 13 -> NONTERM_factor 
    | 14 -> NONTERM_power 
    | 15 -> NONTERM_power 
    | 16 -> NONTERM_power 
    | 17 -> NONTERM_power 
    | 18 -> NONTERM_power 
    | 19 -> NONTERM_vname 
    | 20 -> NONTERM_eof 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 19 
let _fsyacc_tagOfErrorTerminal = 17

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | EQ  -> "EQ" 
  | KW_PRINT  -> "KW_PRINT" 
  | KW_LET  -> "KW_LET" 
  | VNAME _ -> "VNAME" 
  | RBR  -> "RBR" 
  | LBR  -> "LBR" 
  | RBRMOD  -> "RBRMOD" 
  | LBRMOD  -> "LBRMOD" 
  | Bin  -> "Bin" 
  | DivRem  -> "DivRem" 
  | Pow  -> "Pow" 
  | Mul  -> "Mul" 
  | Div  -> "Div" 
  | Sub  -> "Sub" 
  | Sum  -> "Sum" 
  | NUM _ -> "NUM" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | KW_PRINT  -> (null : System.Object) 
  | KW_LET  -> (null : System.Object) 
  | VNAME _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | RBR  -> (null : System.Object) 
  | LBR  -> (null : System.Object) 
  | RBRMOD  -> (null : System.Object) 
  | LBRMOD  -> (null : System.Object) 
  | Bin  -> (null : System.Object) 
  | DivRem  -> (null : System.Object) 
  | Pow  -> (null : System.Object) 
  | Mul  -> (null : System.Object) 
  | Div  -> (null : System.Object) 
  | Sub  -> (null : System.Object) 
  | Sum  -> (null : System.Object) 
  | NUM _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 2us; 65535us; 0us; 1us; 2us; 3us; 2us; 65535us; 0us; 2us; 2us; 2us; 4us; 65535us; 8us; 9us; 28us; 11us; 30us; 12us; 34us; 13us; 6us; 65535us; 8us; 10us; 14us; 15us; 16us; 17us; 28us; 10us; 30us; 10us; 34us; 10us; 9us; 65535us; 8us; 18us; 14us; 18us; 16us; 18us; 19us; 20us; 21us; 22us; 23us; 24us; 28us; 18us; 30us; 18us; 34us; 18us; 10us; 65535us; 8us; 25us; 14us; 25us; 16us; 25us; 19us; 25us; 21us; 25us; 23us; 25us; 26us; 27us; 28us; 25us; 30us; 25us; 34us; 25us; 12us; 65535us; 4us; 5us; 6us; 7us; 8us; 33us; 14us; 33us; 16us; 33us; 19us; 33us; 21us; 33us; 23us; 33us; 26us; 33us; 28us; 33us; 30us; 33us; 34us; 33us; 0us; 65535us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 4us; 7us; 12us; 19us; 29us; 40us; 53us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 2us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 4us; 3us; 4us; 6us; 7us; 4us; 5us; 9us; 10us; 11us; 3us; 6us; 7us; 14us; 3us; 6us; 7us; 15us; 3us; 6us; 7us; 18us; 1us; 6us; 4us; 6us; 9us; 10us; 11us; 1us; 7us; 4us; 7us; 9us; 10us; 11us; 2us; 8us; 13us; 1us; 9us; 2us; 9us; 13us; 1us; 10us; 2us; 10us; 13us; 1us; 11us; 2us; 11us; 13us; 1us; 12us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 17us; 1us; 18us; 1us; 19us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 19us; 23us; 28us; 32us; 36us; 40us; 42us; 47us; 49us; 54us; 57us; 59us; 62us; 64us; 67us; 69us; 72us; 74us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; 92us; |]
let _fsyacc_action_rows = 36
let _fsyacc_actionTableElements = [|2us; 32768us; 2us; 4us; 3us; 6us; 0us; 49152us; 2us; 16385us; 2us; 4us; 3us; 6us; 0us; 16386us; 1us; 32768us; 4us; 35us; 0us; 16387us; 1us; 32768us; 4us; 35us; 1us; 32768us; 1us; 8us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 2us; 16388us; 14us; 16us; 15us; 14us; 3us; 16389us; 10us; 19us; 12us; 21us; 13us; 23us; 3us; 32768us; 5us; 29us; 14us; 16us; 15us; 14us; 3us; 32768us; 7us; 31us; 14us; 16us; 15us; 14us; 2us; 16402us; 14us; 16us; 15us; 14us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 3us; 16390us; 10us; 19us; 12us; 21us; 13us; 23us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 3us; 16391us; 10us; 19us; 12us; 21us; 13us; 23us; 1us; 16392us; 11us; 26us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 1us; 16393us; 11us; 26us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 1us; 16394us; 11us; 26us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 1us; 16395us; 11us; 26us; 0us; 16396us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 0us; 16397us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 0us; 16398us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 0us; 16399us; 0us; 16400us; 0us; 16401us; 5us; 32768us; 4us; 35us; 6us; 28us; 8us; 30us; 9us; 34us; 16us; 32us; 0us; 16403us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 7us; 8us; 10us; 11us; 13us; 15us; 21us; 24us; 28us; 32us; 36us; 39us; 45us; 49us; 55us; 59us; 61us; 67us; 69us; 75us; 77us; 83us; 85us; 86us; 92us; 93us; 99us; 100us; 106us; 107us; 108us; 109us; 115us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 2us; 2us; 4us; 1us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 3us; 3us; 3us; 1us; 1us; 2us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; 4us; 4us; 5us; 5us; 6us; 6us; 6us; 6us; 6us; 7us; 8us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16386us; 65535us; 16387us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16396us; 65535us; 16397us; 65535us; 16398us; 65535us; 16399us; 16400us; 16401us; 65535us; 16403us; |]
let _fsyacc_reductions ()  =    [| 
# 187 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Exp.Program )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 196 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmt)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "CalcParser.fsy"
                                  [_1]
                   )
# 30 "CalcParser.fsy"
                 :  Exp.Program ));
# 207 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'stmt)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data :  Exp.Program )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "CalcParser.fsy"
                                        _1 :: _2
                   )
# 31 "CalcParser.fsy"
                 :  Exp.Program ));
# 219 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "CalcParser.fsy"
                                           Exp.Print(_2)
                   )
# 33 "CalcParser.fsy"
                 : 'stmt));
# 230 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            let _4 = (let data = parseState.GetInput(4) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "CalcParser.fsy"
                                                       Exp.VDecl(_2,_4)
                   )
# 34 "CalcParser.fsy"
                 : 'stmt));
# 242 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "CalcParser.fsy"
                                        _1
                   )
# 37 "CalcParser.fsy"
                 : 'expression));
# 253 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "CalcParser.fsy"
                                                       Exp.Sum (_1, _3)
                   )
# 38 "CalcParser.fsy"
                 : 'expression));
# 265 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "CalcParser.fsy"
                                                       Exp.Sub (_1, _3)
                   )
# 39 "CalcParser.fsy"
                 : 'expression));
# 277 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "CalcParser.fsy"
                                   _1
                   )
# 42 "CalcParser.fsy"
                 : 'tExpression));
# 288 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "CalcParser.fsy"
                                                      Exp.DivRem (_1, _3)
                   )
# 43 "CalcParser.fsy"
                 : 'tExpression));
# 300 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "CalcParser.fsy"
                                                   Exp.Mul (_1, _3)
                   )
# 44 "CalcParser.fsy"
                 : 'tExpression));
# 312 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'tExpression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "CalcParser.fsy"
                                                   Exp.Div (_1, _3)
                   )
# 45 "CalcParser.fsy"
                 : 'tExpression));
# 324 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'power)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "CalcParser.fsy"
                                  _1
                   )
# 48 "CalcParser.fsy"
                 : 'factor));
# 335 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'factor)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'power)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "CalcParser.fsy"
                                             Exp.Pow (_1, _3)
                   )
# 49 "CalcParser.fsy"
                 : 'factor));
# 347 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "CalcParser.fsy"
                                               _2
                   )
# 52 "CalcParser.fsy"
                 : 'power));
# 358 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "CalcParser.fsy"
                                                     Exp.Abs _2
                   )
# 53 "CalcParser.fsy"
                 : 'power));
# 369 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "CalcParser.fsy"
                                Exp.Num(BigAriphmetics.BigInt.convertString _1)
                   )
# 54 "CalcParser.fsy"
                 : 'power));
# 380 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'vname)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "CalcParser.fsy"
                                  Exp.NVar(_1)
                   )
# 55 "CalcParser.fsy"
                 : 'power));
# 391 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "CalcParser.fsy"
                                           Exp.Bin _2
                   )
# 56 "CalcParser.fsy"
                 : 'power));
# 402 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "CalcParser.fsy"
                                   Exp.Var(_1)
                   )
# 59 "CalcParser.fsy"
                 : 'vname));
# 413 "CalcParser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "CalcParser.fsy"
                               1
                   )
# 61 "CalcParser.fsy"
                 : 'eof));
|]
# 424 "CalcParser.fs"
let tables () : FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 20;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Exp.Program  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
